### ISSUE TITLE
Subdomain wildcards

### ISSUE THREAD

**Issue by akaihola** [ray-lothian/UserAgent-Switcher#26]
As suggested in #2, it would be handy to be able to whitelist all subdomains of a domain in one go. I'm using UserAgent-Switcher to make Microsoft Teams calls work on Firefox, and there are a lot of teams and skype subdomains that get accessed.

So in options / white-list mode I'd like to be able to specify:
```
teams.microsoft.com
*.teams.microsoft.com
skype.com
*.skype.com
```

I'll certainly repeat my BTC donation once this feature is released.

**Comment by ray-lothian** [comment]
As of the next release, we will have a new preference in the options page. If it is unchecked, then the extension will consider all the sub-domains when the domain is in either white or black list. I am not adding support for wildcard matching since there is no native method for that and it is going to have performance drawback. I think this will work equally.
