### ISSUE TITLE
BuildID & navigator.* properties

### ISSUE THREAD

**Issue by Westmore-byte** [ray-lothian/UserAgent-Switcher#50]
Hi,

1) Does your extension return an undefined value for BuildID when the faked user agent is not Firefox? The reason is that this is only an attribute that Firefox is sending, hence if the browser is spoofed to non-firefox, that value should not be returned:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/buildID

2) Are you also generating browser specific values for all the navigator.* properties, e.g. navigator.userAgent, etc?

Thank you

**Comment by ray-lothian** [comment]
This extension spoofs a few keys of the navigator object. Since it is practically impossible to follow each browser guideline, as of the 0.3.4 release, there is a new section on the options page of the addon that allows the user to define whatever key that is needed. It is recommended to create an object with all the values set to the target browser and ask the extension to use it instead of the default parser which is limited.

See https://add0n.com/useragent-switcher.html?version=0.3.4#faq15 for more info.
