### ISSUE TITLE
agent list outdated

### ISSUE THREAD

**Issue by TheMastero** [ray-lothian/UserAgent-Switcher#60]
is there a way to update the user agent list ?
As today firefox is already V71 and the addon V68 still, I don't know about other browser versions since I don't use them !

**Comment by kenyoni** [comment]
The whole UAS list is borked. There is no way to add a new entry to the list.  An existing one can be edited and used, but it can't be saved to use again later. The list is obnoxiously long: having a UAS for FF 0.8 is interesting and somewhat amusing for a minute, but totally useless in practice. If you disagree, please give a real-world example.  

With FF now on a 4 week release schedule, this extension would have to be updated every 4 weeks to remain current. Since the UAS list is already 4 releases out of date and the last update was yesterday, I see no hope of this getting accomplished. 

For now, I would recommend: 

[User-Agent Switcher by Alexander Schlarb](https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/?src=search)
It has the most common preset UAS and allows you to add as many new ones as you need/like.

[User-Agent Switcher by Linder](https://addons.mozilla.org/en-US/firefox/addon/user-agent-switcher-revived/?src=search)
It has the most common preset UAS. While the strings are generally for older browser versions, you can edit them and the edits are saved, even if you switch to another UAS and then switch back. You cannot create new UAS with this extension, only edit existing ones.

**Comment by ray-lothian** [comment]
I am going to update the list soon.
